name: Update GitHub Readme Stats

on:
  schedule:
    - cron: '0 0 * * *' # Roda automaticamente todos os dias à meia-noite
  workflow_dispatch: # Permite rodar manualmente a qualquer momento

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão de escrita no repositório
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Generate General Stats Card
        uses: stats-organization/github-readme-stats-action@v1
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        with:
          card: stats
          options: "username=Suami-Yonashiro&show_icons=true&theme=transparent&locale=pt-br&include_all_commits=true&count_private=true"
          token: ${{ secrets.PAT }}
          path: stats.svg

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update readme stats SVGs"
          file_pattern: "*.svg"
